name: an_logger
description: A logging tool that can be customized to output to any location.
version: 1.3.0
homepage: https://github.com/aymtools/an_logger

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:


dev_dependencies:
  lints: any